// authentication types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'
export const USER_LOADING= 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'

// message types
export const SET_MESSAGE = 'SET_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

// User deposit types
export const DEPOSIT_LOADING = 'DEPOSIT_LOADING'
export const DEPOSIT_SUCCESS = 'DEPOSIT_SUCCESS'
export const DEPOSIT_FAILURE = 'DEPOSIT_FAILURE'
export const PROOF_OF_PAY_SUCCESS = 'PROOF_OF_SUCCESS'
export const PROOF_OF_PAY_FAIL = 'PROOF_OF_FAILURE'

// user verification
export const VERIFICATION_LOADING = 'VERIFICATION_LOADING'
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS'
export const VERIFICATION_FAILURE = 'VERIFICATION_FAILURE'


// admin authorize deposit
export const CONFIRM_DEP_LOADING = 'CONFIRM_DEPOSIT_LOADING'
export const CONFIRM_DEP_SUCCESS = 'CONFIRM_DEPOSIT_SUCCESS'
export const CONFIRM_DEP_FAILURE = 'CONFIRM_DEPOSIT_FAILURE'

// admin authorize verification
export const CONFIRM_VER_LOADING = 'CONFIRM_VERIFICATION_LOADING'
export const CONFIRM_VER_SUCCESS = 'CONFIRM_VERIFICATION_SUCCESS'
export const CONFIRM_VER_FAILURE = 'CONFIRM_VERIFICATION_FAILURE'